### ISSUE TITLE
Alert Policy: `region` does not have a default

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-kubernetes-operator#70]
### Description
Currently a user is required to supply the `region` field as part of the `spec` for the `Policy` configuration. This should be not required. 

If the user does not explicitly set a `region`, the default value of `US` should be used.

### Current behavior
When executing `kubectl apply -f ./my-alert-policy.yaml`, the operation appears to have succeeded, however the policy is not created and an error occurs under the hood.

> <small>Note: The command should also fail to execute which has been reported as a bug in issue #45.</small>

### Steps To Reproduce
1. Ensure the operator is installed and ready
1. Use the following `yaml` to configure a minimal Alert Policy (`my-alert-policy.yaml`)
    ```yaml
    apiVersion: nr.k8s.newrelic.com/v1
    kind: Policy
    metadata:
      name: my-policy
    spec:
      api_key: <your API key>
      name: "alert policy created with k8s"
    ```
1. Tail the logs of your controller node - first get the node's full name, then tail those logs
    ```bash
    kubectl describe nodes -n newrelic-kubernetes-operator-system | grep controller-manager
    ```
    ```bash
    kubectl logs -f -n newrelic-kubernetes-operator-system -c manager newrelic-kubernetes-operator-controller-manager-<hash goes here>
    ```
1. Open a new terminal in the current working directory and run 
    ```bash
    kubectl apply -f ./my-alert-policy.yaml
    ```
1. See error - kubernetes will continue to attempt to provision the resource over and over due to the error: `"error":"unknown region"`

### Debug Output (if applicable)
```
{"level":"error", ... ... "msg":"Reconciler error","controller":"policy","request":"default/my-policy","error":"unknown region","stacktrace": ... etc etc
```
